export const ON_MODALCHANGE = "ON_MODALCHANGE";
export const CHANGE_TRANSAMOUNT = "CHANGE_TRANSAMOUNT";
export const CHANGE_DROPDOWN = "CHANGE_DROPDOWN";
export const SET_AUTHKEY = "SET_AUTHKEY";
export const SET_CURRENTACCOUNT = "SET_CURRENTACCOUNT";
export const SET_ALLOTHERACCOUNT = "SET_ALLOTHERACCOUNT";
export const SET_ALLTRANSACTIONS = "SET_ALLTRANSACTIONS ";
export const CHANGE_ACCOUNT = "CHANGE_ACCOUNT";
